# Generated by Django 3.2.9 on 2021-12-07 06:09

import car.models.model_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'brand_models',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'brands',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=car.models.model_utils.upload_image_path)),
            ],
            options={
                'db_table': 'car_gallery',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('F', 'Fixed'), ('A', 'Agreement'), ('I', 'Installments')], default='A', max_length=50)),
                ('price', models.PositiveBigIntegerField(null=True)),
                ('prepayment', models.PositiveBigIntegerField(null=True)),
                ('Amount_per_payment', models.PositiveBigIntegerField(null=True)),
                ('second_prepayment', models.PositiveBigIntegerField(null=True)),
                ('number_of_payments', models.CharField(choices=[(1, '1 pays'), (2, '2 pays'), (3, '3 pays'), (4, '4 pays'), (5, '5 pays'), (6, '6 pays'), (7, '7 pays'), (8, '8 pays'), (9, '9 pays'), (10, '10 pays')], max_length=50, null=True)),
                ('delivery_time', models.IntegerField(choices=[(1, '1 day'), (7, '7 day'), (12, '12 day'), (20, '20 day'), (30, '30 day'), (45, '45 day')], default=1, null=True)),
                ('payment_period', models.IntegerField(choices=[(0, 'every month '), (2, 'every 2 month '), (3, 'every 3 month '), (4, 'every 4 month ')], default=0, null=True)),
            ],
            options={
                'db_table': 'car_price',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_create', models.IntegerField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)], default=2021)),
                ('fuel_type', models.CharField(choices=[('P', 'Petrol'), ('C', 'CNG'), ('H', 'Hybrid'), ('D', 'Diesel')], default='P', max_length=50)),
                ('used_type', models.CharField(choices=[('N', 'Never used'), ('W', 'worked'), ('P', 'Pre cell'), ('C', 'Cortex'), ('R', 'Referred')], default='N', max_length=50)),
                ('kilometer_of_move', models.CharField(blank=True, default='0', max_length=50, null=True)),
                ('body_health_type', models.CharField(choices=[('G', 'Good'), ('D', 'Damaged'), ('U', 'Useless')], default='G', max_length=50)),
                ('descriptions', models.TextField()),
                ('is_free_zone', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'cars',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'colors',
                'managed': False,
            },
        ),
    ]
