# Generated by Django 3.2.9 on 2021-12-01 10:07

import car.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CarPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('price', models.PositiveBigIntegerField()),
                ('prepayment', models.PositiveBigIntegerField()),
                ('Amount_per_payment', models.PositiveBigIntegerField()),
                ('second_prepayment', models.PositiveBigIntegerField()),
                ('number_of_payments', models.CharField(choices=[(1, '1 pays'), (2, '2 pays'), (3, '3 pays'), (4, '4 pays'), (5, '5 pays'), (6, '6 pays'), (7, '7 pays'), (8, '8 pays'), (9, '9 pays'), (10, '10 pays')], max_length=50)),
                ('delivery_time', models.IntegerField(choices=[(1, '1 day'), (7, '7 day'), (12, '12 day'), (20, '20 day'), (30, '30 day'), (45, '45 day')])),
                ('payment_period', models.IntegerField(choices=[(0, 'every month '), (2, 'every 2 month '), (3, 'every 3 month '), (4, 'every 4 month ')])),
            ],
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_create', models.IntegerField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)])),
                ('fuel_type', models.CharField(choices=[('P', 'Petrol'), ('C', 'CNG'), ('H', 'Hybrid'), ('D', 'Diesel')], max_length=50)),
                ('used_type', models.CharField(choices=[('N', 'Never used'), ('W', 'worked'), ('P', 'Pre cell'), ('C', 'Cortex'), ('R', 'Referred')], max_length=50)),
                ('kilometer_of_move', models.CharField(blank=True, default='0', max_length=50, null=True)),
                ('body_health_type', models.CharField(choices=[('G', 'Good'), ('D', 'Damaged'), ('U', 'Useless')], max_length=50)),
                ('descriptions', models.TextField()),
                ('is_free_zone', models.BooleanField(default=False)),
                ('body_color_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_body_color', to='car.colors')),
                ('brand_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.brands')),
                ('inside_color_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_inside_color', to='car.colors')),
                ('price', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='car.carprice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=car.utils.upload_image_path)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='car_image', to='car.cars')),
            ],
        ),
        migrations.CreateModel(
            name='BrandModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_models', to='car.brands')),
            ],
        ),
    ]
