# Generated by Django 3.2.9 on 2021-12-06 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brandmodels',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='brands',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='cargallery',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='carprice',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='cars',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='colors',
            options={'managed': False},
        ),
    ]
