# Generated by Django 3.2.9 on 2021-12-05 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_alter_cars_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carprice',
            name='type',
            field=models.CharField(choices=[('F', 'Fixed'), ('A', 'Agreement'), ('I', 'Installments')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cars',
            name='brand_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.brandmodels'),
        ),
    ]
